apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
  namespace: jenkins
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "auth": "aXNyYWVseG5wOk5hc3AxOTg0QCMkJQ=="
        }
      }
    }

   